server:
  port: 8888
encrypt:
  key: ABCDEFGHIJKLMNOPQRSTUVWXYZ
#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/javaHelper/pluralsight-spring-cloudconfig-wa-tolls
#          default-label: main
#          search-paths:
#            - station*

spring:
  security:
    user:
      name: prateek
      password: prateek
  cloud:
    config:
      server:
        # Needed to keep decryption of connstring
        encrypt:
          enabled: false
        git:
          uri: https://github.com/rseroter/pluralsight-spring-cloudconfig-wa-tolls-2
          search-paths:
            - station*
          repos:
            perf:
              pattern: '*/perf'
              uri: https://github.com/rseroter/pluralsight-spring-cloudconfig-wa-tolls-perf-2
              search-paths:
                - 'station*'

